#!/bin/bash
#SBATCH --partition=bgfsqdr
#SBATCH --job-name=NAB_SRM_11
#SBATCH --time=3:00:00
#SBATCH --output=Output/matlabHTMRM.%j
#SBATCH --name=runNAB
#SBATCH --ntasks=8
#SBATCH --mem=16384

module load apps/matlab/r2019a

date

matlab -nodisplay -nosplash -r "run('runNAB($1,$2,false,true,true,false)')"

date


