#!/bin/bash
nice -n 10 matlab -nodisplay -nosplash -nodesktop -r "run('runNAB(50,52,true,true)')" &
nice -n 10 matlab -nodisplay -nosplash -nodesktop -r "run('runNAB(53,54,true,true)')" &
nice -n 10 matlab -nodisplay -nosplash -nodesktop -r "run('runNAB(55,56,true,true)')" &
nice -n 10 matlab -nodisplay -nosplash -nodesktop -r "run('runNAB(57,58,true,true)')" & 


